//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Burtsev_PR315_Lombard
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphPayStatu
    {
        public int Id { get; set; }
        public Nullable<decimal> SumSell { get; set; }
        public Nullable<System.DateTime> DateSell { get; set; }
        public Nullable<System.DateTime> FactDateSell { get; set; }
        public Nullable<int> IdWorkMan { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual TypeStatu TypeStatu { get; set; }
        public virtual Workman Workman { get; set; }
    }
}
