//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Burtsev_PR315_Lombard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProdutSells = new HashSet<ProdutSell>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> IdWorkMan { get; set; }
        public Nullable<decimal> SumSell { get; set; }
        public Nullable<decimal> SumBuy { get; set; }
    
        public virtual TypeProdut TypeProdut { get; set; }
        public virtual Workman Workman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutSell> ProdutSells { get; set; }
    }
}
